sudo: required
services:
  - docker

before_install:
  - docker build -t guptavishnu/frontend:1.0.0 -f Dockerfile.dev .

script:
  - docker run guptavishnu/frontend:1.0.0 npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app:  "docker-react"
  env:  "DockerReact-env"
  bucket_name:  "elasticbeanstalk-ap-south-1-46685563480"
  bucket_path:  "docker-react"
  on:
    branch: master
  access_key_id:  $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"